name: pidge_on
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rive: ^0.7.22
  firebase_core:
  animated_text_kit: ^4.2.1
  animate_do: ^2.0.0
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+3
  
  provider: ^6.0.1
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.2
  shared_preferences: ^2.0.11
  wakelock: ^0.5.6
  page_transition: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:

flutter_native_splash:


  color: "#ffffff"
  image: assets/pidgeon_splash.png

  

  android: true
  

  android_gravity: center

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/pidgeon.png
    - assets/L1.png
    - assets/L2.png
    - assets/L3.png
    - assets/L4.png
    - assets/L5.png
    - assets/pidgeon_trans.png
    - assets/pidgeon_splash.png
    - assets/emojis.riv
    - assets/flecha.png
    - assets/lecciones.png
    - assets/registro.png
    - assets/santuario.png
    - assets/olivos.png
  fonts:
    - family: Caviar
      fonts:
        - asset: assets/fonts/CaviarDreams.ttf
    - family: Quick
      fonts:
        - asset: assets/fonts/Quicksand_Book.otf
 
  
