List<String> getLyrics() {
  return [
    'Hope stopped the heart',
    'Lost beaten lie',
    'Cold walk the earth',
    'Love faded white',
    'Gave up the war',
    'I\'ve realized',
    'All will become',
    'All will arise',
    'Stay with me',
    'I hear them call the tide',
    'Take me in',
    'I see the last divide',
    'Hopelessy',
    'I leave this all behind',
    'And I am paralyzed',
    'When the broken fall alive',
    'Let the light take me too',
    'When the waters turn to fire',
    'Heaven, please let me through',
    'Far away, far away',
    'Sorrow has left me here',
    'Far away, far away',
    'Tienes que saber que lo ',
    'que estás sintiendo en',
    'estos momentos, lo sienten',
    'millones de personas alrededor',
    'del mundo, y como hemos leído,',
    'nadie ha muerto por sufrir un',
    'ataque de ansiedad, es tan común',
    'que de hecho la ansiedad nos',
    'ha servido por años para poder',
    'Take me in',
    'I see the last divide',
    'Hopelessy',
    'I leave this all behind',
    'And I am paralyzed',
    'When the broken fall alive',
    'Let the light take me too',
    'When the waters…'
  ];
}
